// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://khxakbbpsjktrlzzkajt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtoeGFrYmJwc2prdHJsenprYWp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NTM5MzAsImV4cCI6MjA3MjEyOTkzMH0.8KWlkpeYZxnWLGhyeNwD0vBsSnaKXLA8E5CqWunEZpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});